async function generateGameCertificate(playerId, playerName, year, gameText, rank, totalGames, winrate, points, level) {
  if (!window.jspdf?.jsPDF) {
    alert('jsPDF belum dimuat');
    return;
  }

  const doc = new window.jspdf.jsPDF('l', 'mm', 'a4');

  /* ===== THEME AUTO ===== */
  const g = gameText.toLowerCase();
  let theme;

  if (g === 'uno') {
    theme = {
      bgMain: [17, 24, 39],
      bgHeader: [239, 68, 68],
      accent: [250, 204, 21],
      card: [30, 41, 59],
      textMain: [249, 250, 251],
      textMuted: [203, 213, 225]
    };
  } else if (g === 'poker') {
    theme = {
      bgMain: [2, 6, 23],
      bgHeader: [15, 23, 42],
      accent: [34, 197, 94],
      card: [30, 41, 59],
      textMain: [229, 231, 235],
      textMuted: [148, 163, 184]
    };
  } else {
    theme = {
      bgMain: [15, 23, 42],
      bgHeader: [2, 6, 23],
      accent: [99, 102, 241],
      card: [30, 41, 59],
      textMain: [229, 231, 235],
      textMuted: [148, 163, 184]
    };
  }

  /* ===== BACKGROUND ===== */
  doc.setFillColor(...theme.bgMain);
  doc.rect(0, 0, 297, 210, 'F');

  doc.setFillColor(...theme.bgHeader);
  doc.rect(0, 0, 297, 54, 'F');

  doc.setFillColor(...theme.accent);
  doc.rect(0, 54, 297, 4, 'F');

  /* ===== HEADER ===== */
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...theme.textMain);
  doc.text('GAME PERFORMANCE SUMMARY', 20, 34);

  doc.setFontSize(13);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...theme.textMuted);
  doc.text(`${gameText.toUpperCase()} • SEASON ${year}`, 20, 48);

  /* ===== PLAYER NAME (FOCUS) ===== */
  doc.setFontSize(30);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...theme.textMain);
  doc.text(playerName.toUpperCase(), 148.5, 85, { align: 'center' });

  /* ===== META ===== */
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...theme.textMuted);
  doc.text(`ID: ${playerId}`, 20, 100);
  doc.text(`RANK #${rank}`, 240, 100);

  /* ===== STAT CARDS ===== */
  function statCard(x, y, label, value) {
    doc.setFillColor(...theme.card);
    doc.roundedRect(x, y, 65, 35, 5, 5, 'F');

    doc.setFontSize(10);
    doc.setTextColor(...theme.textMuted);
    doc.text(label, x + 32.5, y + 14, { align: 'center' });

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...theme.textMain);
    doc.text(value, x + 32.5, y + 30, { align: 'center' });
  }

  statCard(40, 120, 'MATCHES', String(totalGames));
  statCard(110, 120, 'WIN RATE', `${winrate}%`);
  statCard(180, 120, 'POINTS', String(points));

  /* ===== ACHIEVEMENT ===== */
  doc.setFillColor(...theme.accent);
  doc.roundedRect(78, 168, 140, 16, 8, 8, 'F');

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...theme.bgMain);
  doc.text(level.toUpperCase(), 148.5, 179, { align: 'center' });

  /* ===== FOOTER (AMAN) ===== */
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...theme.textMuted);
  doc.text('Generated by Sabung Win Rate Calculator', 148.5, 196, { align: 'center' });
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 148.5, 203, { align: 'center' });

  doc.save(`${playerId}_${year}_${gameText}_Performance.pdf`);
}
